### ISSUE TITLE
Text Classification Tests in Kotlin

### ISSUE THREAD

**Issue by SunitRoy2703** [SunitRoy2703/Tensorflow-lite-samples-kotlin#7]
Currently, the Text Classification sample's tests are written in java, we have to change it to Kotlin

Test Link: https://github.com/SunitRoy2703/Tensorflow-lite-kotlin-samples/blob/acf213635ff0e1678b2b08d0afa5814e0fd34c0e/text_classification/app/src/androidTest/java/org/tensorflow/lite/examples/textclassification/UnitTest.java

**Comment by dhruvnagarajan** [comment]
I got this @SunitRoy2703 , assign to me.

**Comment by SunitRoy2703** [comment]
I have assigned this to you @dhruvnagarajan

**Comment by SunitRoy2703** [comment]
It's for keeping all of the models separate and people don't have to worry about build failures in the other modules that they care about. It also makes it less complex to understand a specific sample
